CREATE VIEW V_INSCRITOS
AS SELECT CONCAT(NA.RG,NA.ORGAO_EXP) AS NUM_DOCUMENTO_NAO_ALUNO_INSCRITO, NA.NOME AS NOME_NAO_ALUNO_INSCRITO
FROM  Nao_Alunos_Inscritos nai, Nao_Aluno na
WHERE (nai.RG = na.RG AND nai.Orgao_Exp = na.Orgao_Exp) 
UNION ALL
SELECT A.RA AS NUM_DOCUMENTO_ALUNOS_INSCRITOS, A.NOME AS NOME_ALUNOS_INSCRITOS
FROM ALUNO A, ALUNOS_INSCRITOS AI
WHERE A.RA=AI.RA
UNION ALL 
SELECT PN.CODIGO_PALESTRANTE, PN.NOME AS NOME_PALESTRANTE, P.CARGA_HORARIA, P.DATA, P.TITULO
FROM PALESTRA P, PALESTRANTE PN
WHERE P.CODIGO_PALESTRANTE=PN.CODIGO_PALESTRANTE;
